Repository FLearningg/Flearning_FE, pull requests merged in 2025-05, with the labels that each got.

#2 [FLN-47[Duc][UI] Fix PopupCard Problem #24.05.2025
  FrontEnd/src/components/common/Card/Card.css
  FrontEnd/src/components/common/Card/Card.js
  FrontEnd/src/components/common/Card/PopupCard.js
Labels: bug

#3 [UI][fix] Fix missing dropdown of notification and wishlist
  FrontEnd/public/images/CourseImages.png
  FrontEnd/src/App.js
  FrontEnd/src/assets/header/header.css
  FrontEnd/src/components/footer/Footer.jsx
  FrontEnd/src/components/footer/QuickLinkMobile.jsx
  FrontEnd/src/components/header/Header.jsx
  FrontEnd/src/components/header/HeaderRight.jsx
  FrontEnd/src/components/header/Notification.jsx
  FrontEnd/src/components/header/NotificationCard.jsx
  FrontEnd/src/components/header/WishList.jsx
  FrontEnd/src/components/header/WishListCard.jsx
Labels: bug

#5 [HOTFIX][Duc][UI][PopupCard] Fix card on homepage # 25.5.2025
  FrontEnd/src/components/common/Card/Card.css
Labels: bug

#7 [UI][Feat] Add Admin Dashboard
  FrontEnd/package.json
  FrontEnd/src/assets/AdminDashboard/AdminDashboard.css
  FrontEnd/src/components/AdminDashboard/AdminDashboard.jsx
Labels: Admin

#6 [UI][Feat] Add Student Message
  FrontEnd/src/assets/AdminHeaderAndSidebar/FinalHeaderAndSidebar.css
  FrontEnd/src/assets/AdminHeaderAndSidebar/HeaderMsg.css
  FrontEnd/src/assets/AdminHeaderAndSidebar/Sidebar.css
  FrontEnd/src/assets/StudentMsg/ChatInterface.css
  FrontEnd/src/assets/StudentMsg/StudentMsgGlobal.css
  FrontEnd/src/components/AdminHeaderAndSidebar/FinalHeaderAndSidebar.jsx
  FrontEnd/src/components/AdminHeaderAndSidebar/HeaderMsg.jsx
  FrontEnd/src/components/AdminHeaderAndSidebar/Sidebar.jsx
  FrontEnd/src/components/StudentMessage/ChatInterface.jsx
  FrontEnd/src/components/StudentMessage/StudentMessage.jsx
Labels: Profile
